; PlatformIO Project Configuration
; WiFi-Zugangsdaten in secrets.ini eintragen!

[platformio]
extra_configs = secrets.ini

[env:esp32dev]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
